[package]
name = "trusty"
version = "0.1.0"
authors = ["Andrew McConachie <andrew@depht.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
